name: GitHub Pages CI
on:
  push:
    paths-ignore:
      - '**.png'
      - '**.xml'
      - '**.yml'
      - '**.md'
      - '**.config'
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DocFX Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json      
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GH_PAGES_SECRET }}
          publish_dir: ./docs/_site
