name: .NET CI
on:
  push:
    paths-ignore:
      - '**.yml'
      - '**.md'
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build .NET library (release)
      run: dotnet build --configuration Release --no-restore

# [To-do]: add unit tests later.
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
